version: '3'

services:
  nats-server: 
    image: nats:latest
    ports:
      # - "4222:4222"
      - "8222:8222"
      # - "6222:6222"

  api-gateway:
    build: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:3003"
    volumes:
      - ./api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3003
      - NATS_SERVERS=nats://nats-server:4222

  products-ms:
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
   depends_on:
    - orders-db
   build: ./orders-ms
   volumes:
    - ./orders-ms/src:/usr/src/app/src
   command: npm run start:dev
   environment:
    - PORT=3000
    - NATS_SERVERS=nats://nats-server:4222
    - DATABASE_URL=postgresql://${ORDERS_DB_USER}:${ORDERS_DB_PASSWORD}@orders-db:5432/${ORDERS_DB_NAME}

  orders-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${ORDERS_DB_USER}
      - POSTGRES_PASSWORD=${ORDERS_DB_PASSWORD}
      - POSTGRES_DB=${ORDERS_DB_NAME}

  payments-ms:
    container_name: payments-ms
    build: ./payments-ms
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: pnpm run start:dev
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SECRET_SIGNATURE=${STRIPE_SECRET_SIGNATURE}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - PAYMENTS_MS_URL=${PAYMENTS_MS_URL}
